backend:
  name: git-gateway
  branch: main

publish_mode: simple
media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    label_singular: "Post"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "hidden", default: ["posts"] }
      - { label: "Body", name: "body", widget: "markdown" }
